name: Build Check

on:
  pull_request:
    paths-ignore:
      - 'ios/**'
      - 'readme.md'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v4

      - name: use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: install dependencies
        run: npm ci

      - name: build Nuxt project
        run: npm run generate

      - name: copy to Android project
        run: npx cap sync

      - name: compile Android app
        run: ./android/gradlew assembleDebug -p android --no-daemon
